name: Deploy Frontend Only

on:
  push:
    branches: ["main"]
    paths:
      - "Frontend/**" # Chỉ chạy khi có thay đổi trong thư mục Frontend

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync Frontend to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.IF_HOST }}
          username: ${{ secrets.IF_USER }}
          password: ${{ secrets.IF_PASS }}

          # Lấy code từ thư mục Frontend trên GitHub
          local-dir: ./frontend/

          # Đẩy vào thư mục gốc htdocs trên Server
          server-dir: htdocs/

          # CỰC KỲ QUAN TRỌNG: Để false để nó KHÔNG xóa file api.php của Backend
          dangerous-clean-slate: false
