name: Deploy Backend Only

on:
  push:
    branches: ["main"]
    paths:
      - "Backend/**" # Chỉ chạy khi có thay đổi trong thư mục Backend

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync Backend to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.IF_HOST }}
          username: ${{ secrets.IF_USER }}
          password: ${{ secrets.IF_PASS }}

          # Lấy code từ thư mục Backend trên GitHub
          local-dir: ./backend/

          # Đẩy vào thư mục gốc htdocs trên Server
          server-dir: htdocs/

          # CỰC KỲ QUAN TRỌNG: Để false để nó KHÔNG xóa file index.html của Frontend
          dangerous-clean-slate: false
